# Generated by Django 5.2.6 on 2025-09-17 14:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_title', models.CharField(default='Get In Touch', max_length=100)),
                ('header_description', models.TextField(default="Ready to start your next project? We'd love to hear from you. Send us a message and we'll respond as soon as possible.")),
                ('address', models.TextField(default='123 Broadway Street\nNew York, NY 10001')),
                ('phone', models.CharField(default='+1 (555) 123-4567', max_length=50)),
                ('email', models.EmailField(default='hello@digitalexp.com', max_length=254)),
                ('hours', models.TextField(default='Mon - Fri: 9:00 AM - 6:00 PM\nSat - Sun: 10:00 AM - 4:00 PM')),
                ('map_embed_url', models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d193595.15830869428!2d-74.119763973046!3d40.69766374874431!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sus!4v1642678645193!5m2!1sen!2sus', help_text='Google Maps embed URL')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faqs',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Emoji icon', 'max_length': 10}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_images',
            field=wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(default='Get Started Today', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(default='We create cutting-edge solutions that transform how businesses connect with their customers through innovative technology and design'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Revolutionizing Digital Experiences', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_description',
            field=models.TextField(default='Subscribe to our newsletter and get the latest updates, tips, and exclusive offers delivered to your inbox.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_title',
            field=models.CharField(default='Stay Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats',
            field=wagtail.fields.StreamField([('stat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('number', 0), ('label', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 0), ('quote', 1), ('image', 2)]], {})}),
        ),
    ]
