# Generated by Django 5.2.6 on 2025-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactpage_homepage_faqs_homepage_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(blank=True, default='/contact/', null=True),
        ),
    ]
