# Generated by Django 5.2.6 on 2025-09-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_hero_cta_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='features',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials',
        ),
    ]
