# Generated by Django 5.2.6 on 2025-09-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_faqs_remove_homepage_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
    ]
