# Generated by Django 5.2.6 on 2025-09-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_hero_cta_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='map_embed_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
    ]
